### ISSUE TITLE
New Web Framework? it strips things back to a delicate balance of simplicity and power.

### ISSUE THREAD

**Issue by aiamk** [lonnieezell/monarch#10]
are you trying to fix the mistakes you did in codeigniter 4?
would you admit it?

just an advice, you can enhance & fix codeigniter 3 to work with new PHP versions   instead of wasting your time building a new one.

codeiginter community still loves CI3.

you went so far with codeigniter 4, PHP is a glue language, keep it simple.

sorry bro but i had to say that.
peace

**Comment by lonnieezell** [comment]
Oh, I'll admit my choices on there weren't perfect, and they weren't all mine, either. They did bring it into a new age and modernize the code, sometimes for the better sometimes not. And I feel that when 4 was first released it still kept much more with the feeling of 3, though you did need a few concepts. Not all changes since the first release have kept with that, to be fair. 

But this isn't really meant for general consumption. As the README says, this is an experiment. This is me trying to find what I would really love to work with on personal projects. But it's just an experiment, a playground if you will. Someplace I come to from time to time to "unwind" from all of the other pressures and stresses in life. 

Thanks for your input, though. It's always appreciated.
